export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCESS = "ALL_PRODUCT_SUCESS";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";


export const PRODUCT_DETAIL_REQUEST = "PRODUCT_DETAIL_REQUEST";
export const PRODUCT_DETAIL_SUCESS = "PRODUCT_DETAIL_SUCESS";
export const PRODUCT_DETAIL_FAIL = "PRODUCT_DETAIL_FAIL";





export const CLEAR_ERROR="CLEAR_ERRROR";